In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('datasets/cwurData.csv')
df.head()

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012

In [35]:
# define a function to categorize the rank into rank levels
def categorize_rank(rank): 
    if rank <=100: 
        return "First Tier"
    elif (rank >100) & (rank <=200):
        return "Second Tier"
    elif (rank >200) & (rank <=300):
        return "Third Tier"
    return "Other Top Tier"

In [36]:
df['rank_tier'] = df['world_rank'].apply( lambda x: categorize_rank(x))

In [46]:
df.pivot_table(index = 'country',columns = 'rank_tier', values = 'score', aggfunc = [np.mean, np.max], margins =True).head()

                mean                                                   \
rank_tier First Tier Other Top Tier Second Tier Third Tier        All
country
Argentina        NaN      44.672857         NaN        NaN  44.672857
Australia    47.9425      44.645750     49.2425  47.285000  45.825517
Austria          NaN      44.864286         NaN  47.066667  45.139583
Belgium      51.8750      45.081000     49.0840  46.746667  47.011000
Brazil           NaN      44.499706     49.5650        NaN  44.781111

                amax
rank_tier First Tier Other Top Tier Second Tier Third Tier    All
country
Argentina        NaN          45.66         NaN        NaN  45.66
Australia      51.61          45.97       50.40      47.47  51.61
Austria          NaN          46.29         NaN      47.78  47.78
Belgium        52.03          46.21       49.73      47.14  52.03
Brazil           NaN          46.08       49.82        NaN  49.82

In [ ]:
df.aggregate