In [1]:
import pandas as pd

kyphosis_dataset = pd.read_csv("kyphosis.csv")

In [2]:
kyphosis_dataset.head(2)

  Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14

In [3]:
kyphosis_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Kyphosis  81 non-null     object
 1   Age       81 non-null     int64
 2   Number    81 non-null     int64
 3   Start     81 non-null     int64
dtypes: int64(3), object(1)
memory usage: 2.7+ KB

In [4]:
kyphosis_dataset.describe()

              Age     Number      Start
count   81.000000  81.000000  81.000000
mean    83.654321   4.049383  11.493827
std     58.104251   1.619423   4.883962
min      1.000000   2.000000   1.000000
25%     26.000000   3.000000   9.000000
50%     87.000000   4.000000  13.000000
75%    130.000000   5.000000  16.000000
max    206.000000  10.000000  18.000000

In [5]:
kyphosis_dataset['Kyphosis'].unique()

array(['absent', 'present'], dtype=object)

In [6]:
kyphosis_dataset

   Kyphosis  Age  Number  Start
0    absent   71       3      5
1    absent  158       3     14
2   present  128       4      5
3    absent    2       5      1
4    absent    1       4     15
..      ...  ...     ...    ...
76  present  157       3     13
77   absent   26       7     13
78   absent  120       2     13
79  present   42       7      6
80   absent   36       4     13

[81 rows x 4 columns]

In [7]:
target_transformed = pd.get_dummies(kyphosis_dataset['Kyphosis'])
target_transformed
target_transformed.index
kyphosis_dataset.index
#type(target_transformed)
type(kyphosis_dataset)

pandas.core.frame.DataFrame

In [8]:
#kyphosis_dataset.merge(target_transformed, how = 'inner' left_index =True,right_index = True )
merged_dataset = kyphosis_dataset.merge(right =target_transformed, how = 'inner', left_index = True, right_index =True)

In [9]:
merged_dataset.drop(labels ='Kyphosis', axis =1, inplace =True)

In [10]:
merged_dataset['Age'].aggregate(['min', 'max', 'mean'])

min       1.000000
max     206.000000
mean     83.654321
Name: Age, dtype: float64

In [11]:
merged_dataset['Age']=merged_dataset['Age'].astype(dtype =float)

In [12]:
def months_to_years(months):
    years=months/12
    return years

In [13]:
merged_dataset['Age in Years'] =merged_dataset['Age'].apply(months_to_years)

In [14]:
merged_dataset[ merged_dataset['Age'] ==merged_dataset['Age'].min()]

    Age  Number  Start  absent  present  Age in Years
4   1.0       4     15       1        0      0.083333
5   1.0       2     16       1        0      0.083333
13  1.0       4     12       1        0      0.083333
15  1.0       3     16       1        0      0.083333
36  1.0       3      9       1        0      0.083333

In [15]:
merged_dataset[ merged_dataset['Age'] ==merged_dataset['Age'].max()]

      Age  Number  Start  absent  present  Age in Years
73  206.0       4     10       1        0     17.166667

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [20]:
merged_dataset['Age'] = scaler.fit_transform(merged_dataset['Age'].values.reshape(-1,1))

In [23]:
merged_dataset['Age'].describe().round(2)

count    81.00
mean      0.00
std       1.01
min      -1.43
25%      -1.00
50%       0.06
75%       0.80
max       2.12
Name: Age, dtype: float64