In [23]:
# Inner Join
import pandas as pd
#Create two dataframes
df_staff = pd.DataFrame( [ { 'Name': 'Kelly', 'Role': "Director of HR"}, 
                                                                 { 'Name': 'Sally', 'Role': "Course Liason"},
                                                                 { 'Name': 'James', 'Role': "Grader"}
                                                                ])
df_staff = df_staff.set_index(keys ='Name')
print(df_staff)

                 Role
Name
Kelly  Director of HR
Sally   Course Liason
James          Grader

In [24]:
#Create the second
df_students = pd.DataFrame( [ { 'Name': 'James', 'School': "Business"}, 
                                                                 { 'Name': 'Mike', 'School': "Law"},
                                                                 { 'Name': 'Sally', 'School': "Engineering"}
                                                                ])
df_students = df_students.set_index(keys ='Name')

In [28]:
# if we want the union 
print(pd.merge(left = df_staff, right = df_students, how = 'outer', left_on = 'Name', right_on = 'Name'))
print(pd.merge(left = df_staff, right = df_students, how = 'outer', left_index = True, right_index = True))

                 Role       School
Name
Kelly  Director of HR          NaN
Sally   Course Liason  Engineering
James          Grader     Business
Mike              NaN          Law
                 Role       School
Name
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally   Course Liason  Engineering

In [29]:
print(pd.merge(left = df_staff, right = df_students, how = 'inner', left_index = True, right_index = True))

                Role       School
Name
Sally  Course Liason  Engineering
James         Grader     Business

In [31]:
#Examples of Set Addition
#1. List of all staff regardless of whether they are students or not. If they were students, we would want to get student details
#2 List of all students regardless of whehter they were staff or not
pd.merge(left = df_staff, right = df_students, how = 'left', left_index = True, right_index = True)

                 Role       School
Name
Kelly  Director of HR          NaN
Sally   Course Liason  Engineering
James          Grader     Business

In [33]:
pd.merge(left = df_staff, right = df_students, how = 'right', left_index = True, right_index = True)

                Role       School
Name
James         Grader     Business
Mike             NaN          Law
Sally  Course Liason  Engineering