In [139]:
def clean_country(country_name):
        #string =  'Bolivia9 (Plurinational State of)' 
        
        #print(country_first_name)
        
        #pattern = '([a-zA-Z]*)(?=[0-9])'
        
        string_array_len = len(country_name.split(sep = '('))
        
        print("String split length", string_array_len)

        
        if  string_array_len>1:
            country_name =country_name.split(sep = '(')[0]
            country_name= country_name.strip()
            print("Parenthesis cleaned, first name assigned",country_name)
        elif string_array_len <=1 :
            country_name = country_name
            print(country_name) 
        print(country_name)    
                
        import regex as re
        
        pattern = '(^[^0-9]*)(?=[0-9]+)'
        pattern_matches = re.findall(pattern, country_name )
        b = len(pattern_matches)
        
        print("pattern_matches", b)
        for i in pattern_matches:
            print(i)
              
        if b >= 1:
            country_name = pattern_matches[0]
        elif b<1:
            country_name =country_name
        
        return country_name

In [141]:
clean_country(country_name = 'Japan1')

String split length 1
Japan1
Japan1
pattern_matches 1
Japan

'Japan'

In [82]:
clean_country(country_name = 'Italy9')

String split length 1
Italy9
Italy9
pattern_matches 1

'Italy'

In [41]:
clean_country(country_name = 'Italy9 ()')

String split length 2
Parenthesis cleaned, first name assigned Italy9
Italy9

'Italy9'

In [152]:
import pandas as pd
A = pd.DataFrame(['Vietnam','United States','Iran','South Korea'],index = range(4))
B = pd.DataFrame(['Viet nam','United States','Iran','Korea','Japan'],index = range(5))
C = pd.DataFrame(['Viet nam','United States','Iran','Indonesia'])
A.rename(columns={0:'Country'},inplace=True)
B.rename(columns={0:'Country Name'},inplace=True)
C.rename(columns={0:'Country Name'},inplace=True) 

D = pd.merge(A,B,how='outer',left_on='Country',right_on='Country Name')
E = pd.merge(C,D,how='outer',left_on='Country Name',right_on='Country')

display(E)
#display(E)

D1 = pd.merge(A,B,how='inner',left_on='Country',right_on='Country Name')
E1 = pd.merge(C,D1,how='inner',left_on='Country Name',right_on='Country')

print(len(E)-len(E1))
print(len(E))
print(len(E1))

B.rename(columns={'Country Name':'Country'},inplace=True)
C.rename(columns={'Country Name':'Country'},inplace=True) 
D = pd.merge(A,B,how='outer',left_on='Country',right_on='Country')
E = pd.merge(C,D,how='outer',left_on='Country',right_on='Country')
display(E)
D1 = pd.merge(A,B,how='inner',on ='Country')
E1 = pd.merge(C,D1,how='inner',on='Country')

print(len(E)-len(E1))
print(len(E))
print(len(E1))

  Country Name_x        Country Country Name_y
0       Viet nam            NaN            NaN
1  United States  United States  United States
2           Iran           Iran           Iran
3      Indonesia            NaN            NaN
4            NaN        Vietnam            NaN
5            NaN    South Korea            NaN
6            NaN            NaN       Viet nam
7            NaN            NaN          Korea
8            NaN            NaN          Japan

7
9
2

         Country
0       Viet nam
1  United States
2           Iran
3      Indonesia
4        Vietnam
5    South Korea
6          Korea
7          Japan

6
8
2